[package]
name = "wrt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wrt"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
